apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-nodejs-argocd
  newName: faizanmomin2508/aks-nodejs-argocd
  newTag: 5fa3e36227ac4a39d50202f7d8400636be8ea806
